version: "3"
services:
  server:
    build: ./server
    restart: always
    command: "/bin/bash -c 'bundle exec rackup --host 0.0.0.0 --port 3000'"
    volumes:
      - ./server/:/app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    environment:
      RACK_ENV: development
  front:
    build: ./front
    command: "/bin/bash -c 'ember serve'"
    volumes:
      - ./front/mlabs:/app
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: mlabs
      POSTGRES_USER: mlabs