default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  username: mlabs
  password: mlabs
  host: db

development:
  <<: *default
  database: mlabs_development

test:
  <<: *default
  database: mlabs_test