source 'https://rubygems.org'

ruby '2.6.4'

gem 'rake'
gem 'grape'

gem 'activerecord', require: 'active_record'
gem 'otr-activerecord'
gem 'pg'

gem 'rspec'
gem 'capybara'
gem 'shoulda-matchers', require: false