require 'rubygems'

require 'bundler/setup'

require 'rake'

load "tasks/otr-activerecord.rake"


task :environment do
  ENV['RACK_ENV'] ||= 'development'
  require File.expand_path('config/environment', __dir__)
end

namespace :db do
  # Some db tasks require your app code to be loaded; they'll expect to find it here
  task :environment do
    require File.expand_path('config/environment', __dir__)
  end
end